### ISSUE TITLE
Create task-specific tutorials

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/vue-pybossa-frontend#183] opened 2017-08-31 15:59 UTC
For re-use in multiple projects e.g. a mark tutorial for use in all mark projects. 

It should very briefly explain what the task is, why do it, and ideally include an animated gif of the process. Refer users to help for more specific information about what to include or exclude etc.

**Comment by mialondon** [comment] 2017-09-05 17:09
Some images for use in tutorials and help documents
![largetextisnottitle](https://user-images.githubusercontent.com/380763/30073234-0582b94c-9265-11e7-806a-05561ccfa957.png)

![select titles cropped playbills_project_identify_titles_theatre_royal_margate_179](https://user-images.githubusercontent.com/380763/30073314-3e6b0c46-9265-11e7-8d6f-7ffe052950c1.png)

![row playbills access_bl_uk_item_viewer_ark__81055_vdc_100022589132_0x000002 _c 0](https://user-images.githubusercontent.com/380763/30073339-59e1f73c-9265-11e7-9124-f11ab0001e3b.png)

**Comment by mialondon** [comment] 2017-09-06 15:28
![access_bl_uk_item_viewer_ark__81055_vdc_100022589190_0x000002](https://user-images.githubusercontent.com/380763/30120308-5ce247dc-9320-11e7-9d3c-c251e05baa46.png)
Image of playbills in situ on the walls of a theatre in Portsmouth

**Comment by mialondon** [comment] 2017-09-06 15:38
![playbills_crop_screenshot_2017-09-01t09-12-34 025z](https://user-images.githubusercontent.com/380763/30120798-ceeaf9fe-9321-11e7-8008-1623b0578326.png)
'Agreeable surprise'!

**Comment by alexandermendes** [comment] 2017-09-19 17:44
So this is another duplicate of the various "update tutorial" issues we have scattered around...e.g. https://github.com/LibCrowds/project-playbills/issues/11

**Closed by alexandermendes** 2017-09-19 17:44 UTC
Labels: content, enhancement
